name: Deploy Client

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.*"
      - "tsconfig*.json"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SSH_HOST: ${{ secrets.CLIENT_SSH_HOST }}
      SSH_USER: ${{ secrets.CLIENT_SSH_USER }}
      SSH_PORT: ${{ secrets.CLIENT_SSH_PORT }}
      SSH_KEY: ${{ secrets.CLIENT_SSH_KEY }}
      REMOTE_PATH: /var/www/client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          printf "%s" "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${SSH_PORT:-22} "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Ensure remote directory
        run: |
          ssh -i ~/.ssh/id_rsa -p ${SSH_PORT:-22} ${SSH_USER}@${SSH_HOST} "mkdir -p ${REMOTE_PATH}/dist"

      - name: Rsync dist to droplet
        run: |
          rsync -az --delete -e "ssh -p ${SSH_PORT:-22} -i ~/.ssh/id_rsa" dist/ ${SSH_USER}@${SSH_HOST}:${REMOTE_PATH}/dist/
